### ISSUE TITLE
Assertion `buf == table->record[0]' fails in virtual int ha_rocksdb::delete_row(const uchar*)

### ISSUE THREAD

**Issue by elenst** [MySQLOnRocksDB/mysql-5.6#76]
### Test case

```
CREATE TABLE t1 (pk INT PRIMARY KEY, f1 INT) ENGINE=RocksDB;
CREATE TABLE t2 (pk INT PRIMARY KEY, f1 INT) ENGINE=RocksDB;

CREATE TRIGGER tr AFTER DELETE ON t1 FOR EACH ROW DELETE FROM t2 WHERE pk = old.pk; 

INSERT INTO t1 VALUES (1,1);
REPLACE INTO t1 VALUES (1,2); 

# Cleanup

SELECT * FROM t1;
DROP TABLE t1, t2;

```
### Stack trace from commit fe4820cc100

```
mysqld: storage/rocksdb/ha_rocksdb.cc:4350: virtual int ha_rocksdb::delete_row(const uchar*): Assertion `buf == table->record[0]' failed.
00:27:01 UTC - mysqld got signal 6 ;
```

```
#5  0x00007fab346d583b in __GI_abort () at abort.c:91
#6  0x00007fab346cad9e in __assert_fail_base (fmt=<optimized out>, assertion=0x12c92cb "buf == table->record[0]", file=0x12c7748 "storage/rocksdb/ha_rocksdb.cc", line=<optimized out>, function=<optimized out>) at assert.c:94
#7  0x00007fab346cae42 in __GI___assert_fail (assertion=0x12c92cb "buf == table->record[0]", file=0x12c7748 "storage/rocksdb/ha_rocksdb.cc", line=4350, function=0x12cac20 "virtual int ha_rocksdb::delete_row(const uchar*)") at assert.c:103
#8  0x0000000000bd437b in ha_rocksdb::delete_row(unsigned char const*) () at storage/rocksdb/ha_rocksdb.cc:4350
#9  0x0000000000735887 in handler::ha_delete_row(unsigned char const*) () at sql/handler.cc:7641
#10 0x00000000008ae836 in write_record(THD*, TABLE*, COPY_INFO*, COPY_INFO*) () at sql/sql_insert.cc:1843
#11 0x00000000008ac749 in mysql_insert(THD*, TABLE_LIST*, List<Item>&, List<List<Item> >&, List<Item>&, List<Item>&, enum_duplicates, bool) () at sql/sql_insert.cc:1030
#12 0x00000000008ce51d in mysql_execute_command(THD*, unsigned long long*, unsigned long long*) () at sql/sql_parse.cc:3951
#13 0x00000000008d68da in mysql_parse(THD*, char*, unsigned int, Parser_state*, unsigned long long*, char*) () at sql/sql_parse.cc:7002
#14 0x00000000008c86fb in dispatch_command(enum_server_command, THD*, char*, unsigned int) () at sql/sql_parse.cc:1515
#15 0x00000000008c7345 in do_command(THD*) () at sql/sql_parse.cc:1065
#16 0x000000000088ea96 in do_handle_one_connection(THD*) () at sql/sql_connect.cc:1021
#17 0x000000000088e549 in handle_one_connection () at sql/sql_connect.cc:929
#18 0x00007fab352f2e9a in start_thread (arg=0x7fab3018e700) at pthread_create.c:308
#19 0x00007fab3478f8bd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
```

```
Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Last run query buffer: ^CREPLACE INTO t1 VALUES (1,2)
Query (7faafc0053a0): REPLACE INTO t1 VALUES (1,2)
Connection ID (thread ID): 2
Status: NOT_KILLED
```

**Comment by yoshinorim** [comment]
Thanks for the bug report. Verified as described with debug build.

**Comment by spetrunia** [comment]
https://reviews.facebook.net/D40779
